### ISSUE TITLE
Compilation of a simple .toc file fails.

### ISSUE THREAD

**Issue by chr15m** [jduey/toccata#8]
```
$ cat testme.toc 
(defn hello [stuff]
  (print stuff))
$ ./toccata testme.toc > testme.c

*** compilation failed  don't know where
Aborted (core dumped)
```

Is this because there is no `main`? Am I able to use this to compile code that will be linked in to another binary?

**Comment by jduey** [comment]
Oh wow. Somebody actually tried to use that. :)

That is very old and I'm even sure what the status of the repo is. I've been working very hard on a private repo and plan to do a public release in May. I'd say not to waste your time trying to get the old stuff working and stay tuned for when the new stuff comes out.

But seriously thanks for trying it out. I think the stuff I'm going to release is going to be really exciting and worth the wait.

**Comment by chr15m** [comment]
@jduey wow that is exciting! will keep an eye out for it.
